onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /testbench/dut/clk
add wave -noupdate /testbench/dut/rst_n
add wave -noupdate /testbench/dut/pc
add wave -noupdate /testbench/dut/halt
add wave -noupdate /testbench/dut/PC
add wave -noupdate /testbench/dut/aluN
add wave -noupdate /testbench/dut/aluZ
add wave -noupdate /testbench/dut/aluV
add wave -noupdate /testbench/dut/N
add wave -noupdate /testbench/dut/Z
add wave -noupdate /testbench/dut/V
add wave -noupdate /testbench/dut/instruction
add wave -noupdate /testbench/dut/rf_wrData
add wave -noupdate /testbench/dut/rf_data1
add wave -noupdate /testbench/dut/rf_data2
add wave -noupdate /testbench/dut/alu_outData
add wave -noupdate /testbench/dut/updatePC
add wave -noupdate /testbench/dut/haltpc
add wave -noupdate /testbench/dut/newPC
add wave -noupdate /testbench/dut/inPC
add wave -noupdate /testbench/dut/EXMEMpc
add wave -noupdate /testbench/dut/PCwr
add wave -noupdate /testbench/dut/EXMEMopcode
add wave -noupdate /testbench/dut/MEMWBopcode
add wave -noupdate /testbench/dut/IMen
add wave -noupdate /testbench/dut/wrIFID
add wave -noupdate /testbench/dut/IFIDclear
add wave -noupdate /testbench/dut/instruct
add wave -noupdate /testbench/dut/IFIDpc
add wave -noupdate /testbench/dut/opcode
add wave -noupdate /testbench/dut/MemWrite
add wave -noupdate /testbench/dut/MemRead
add wave -noupdate /testbench/dut/RegWrite
add wave -noupdate /testbench/dut/MemtoDist
add wave -noupdate /testbench/dut/MEMWBrd
add wave -noupdate /testbench/dut/MEMWBRegWrite
add wave -noupdate /testbench/dut/rf_addr1
add wave -noupdate /testbench/dut/rf_addr2
add wave -noupdate /testbench/dut/wrIDEX
add wave -noupdate /testbench/dut/IDEXclear
add wave -noupdate /testbench/dut/IDEXMemRead
add wave -noupdate /testbench/dut/IDEXMemWrite
add wave -noupdate /testbench/dut/IDEXMemtoReg
add wave -noupdate /testbench/dut/IDEXRegWrite
add wave -noupdate /testbench/dut/IDEXpc
add wave -noupdate /testbench/dut/readData1out
add wave -noupdate /testbench/dut/readData2out
add wave -noupdate /testbench/dut/shiftamt
add wave -noupdate /testbench/dut/IDEXrs
add wave -noupdate /testbench/dut/IDEXrt
add wave -noupdate /testbench/dut/IDEXrd
add wave -noupdate /testbench/dut/IDEXopcode
add wave -noupdate /testbench/dut/rd_in_or_15
add wave -noupdate /testbench/dut/branchcondout
add wave -noupdate /testbench/dut/branchoffout
add wave -noupdate /testbench/dut/calloffsetout
add wave -noupdate /testbench/dut/EXMEMRegWrite
add wave -noupdate /testbench/dut/EXMEMrd
add wave -noupdate /testbench/dut/forA
add wave -noupdate /testbench/dut/forB
add wave -noupdate /testbench/dut/EXMEMout
add wave -noupdate /testbench/dut/inputEXMEMdata
add wave -noupdate /testbench/dut/alu1Input
add wave -noupdate /testbench/dut/alu2Input
add wave -noupdate /testbench/dut/branchConditionIsTrue
add wave -noupdate /testbench/dut/wrEXMEM
add wave -noupdate /testbench/dut/EXMEMclear
add wave -noupdate /testbench/dut/PCsrc
add wave -noupdate /testbench/dut/EXMEMmemRead
add wave -noupdate /testbench/dut/EXMEMmemWrite
add wave -noupdate /testbench/dut/EXMEMmemtoReg
add wave -noupdate /testbench/dut/dataMemWrData
add wave -noupdate /testbench/dut/dtMemReadData
add wave -noupdate /testbench/dut/wrMEMWB
add wave -noupdate /testbench/dut/MEMWBclear
add wave -noupdate /testbench/dut/MEMWBMemtoReg
add wave -noupdate /testbench/dut/alu_res
add wave -noupdate /testbench/dut/dataMemresl
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {105 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 211
configure wave -valuecolwidth 80
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {246 ns}
